TestApp/config/routes.rb
TestApp::Application.routes.draw do
  get "welcome/index"

  resources :pictures

  resources :posts do
    resources :comments
  end
  root 'welcome#index'

end

TestApp/app/models/archivo.rb
class Archivo < ActiveRecord::Base
end

TestApp/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  before_destroy :time_validation


  def time_validation
    return true if Time.now - created_at <= 2.minutes
    errors.add :base, "No se puede eliminar luego de pasados 2 minutos"
    false
  end
  
  
end

TestApp/app/models/picture.rb
class Picture < ActiveRecord::Base

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#>" },
                    :default_url => "/images/:style/missing.png",
                    :storage => :dropbox,
                    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
                    :dropbox_options => {:path => proc {|style| "files/#{id}/#{avatar.original_filename}"}}
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

TestApp/app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  #has_many :tags, limit: 5
  validates :title, presence: true
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#>" },
                    :default_url => "/images/:style/missing.png",
                    :storage => :dropbox,
                    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
                    :dropbox_options => {:path => proc {|style| "files/#{id}/#{avatar.original_filename}"}}
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

TestApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

TestApp/app/controllers/archivos_controller.rb
class ArchivosController < ApplicationController
end

TestApp/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
  	@post = Post.find(params[:post_id])
  	@comment = Comment.find(params[:id])
  	
    @comment.destroy
    redirect_to post_path(@post)

  end

  private
    def comment_params
      params.require(:comment).permit(:user, :body)
    end
end

TestApp/app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def new

  end

  def create
    @picture = Picture.new(picture_params)

    @picture.save
    redirect_to @picture
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def index
    @picture = Picture.all
  end

  private
  def picture_params
    params.require(:picture).permit(:title, :avatar)
  end

end

TestApp/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
  end

  def create
    @post = Post.new(post_params)

    @post.save
    redirect_to @post
  end

  def show
    @post = Post.find(params[:id])
  end

  def index
    @post = Post.all
  end

  def by_tags
  
  end

  def set_post
    @post = Post.find(params[:id])
  end

  private
  def post_params
    params.require(:post).permit(:title, :user, :text, :tag1, :tag2, :tag3, :tag4, :tag5, :avatar)
  end



end

TestApp/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

TestApp/app/helpers/application_helper.rb
module ApplicationHelper
end

TestApp/app/helpers/archivos_helper.rb
module ArchivosHelper
end

TestApp/app/helpers/comments_helper.rb
module CommentsHelper
end

TestApp/app/helpers/pictures_helper.rb
module PicturesHelper
end

TestApp/app/helpers/posts_helper.rb
module PostsHelper
end

TestApp/app/helpers/welcome_helper.rb
module WelcomeHelper
end

TestApp/app/views/comments/new.html.erb
<h1 align="center">Nuevo Comentario</h1>

<%= form_for :comment, url: comment_path do |f| %>

    <p align="center">
      <%= f.label :user %><br>
      <%= f.text_field :user %>
    </p>

    <p align="center">
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

<% end %>

TestApp/app/views/comments/show.html.erb
<p>
  <strong>Autor:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @comment.text %>
</p>

TestApp/app/views/images/new.html.erb
<h1>Subir una imagen nueva</h1>

<%= form_for :image, url: images_path do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p align="center">
      <%= f.file_field :avatar %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

TestApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TestApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">TestApp</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Posts", posts_path  %></li>
              <li><%= link_to "Imagenes", pictures_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
 <!--            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li>link1</li>

              </ul>
            </div>-->
            <!--/.well --> 
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; TestApp 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

TestApp/app/views/pictures/index.html.erb
<h1>Menu Imagenes</h1>

<%= link_to 'Nueva Imagen', new_picture_path %>

<table>
  <% @picture.each do |picture| %>
      <tr>
        <td><%= picture.title %></td>
      </tr>
  <% end %>
</table>

TestApp/app/views/pictures/new.html.erb
<h1>Subir una imagen nueva</h1>

<%= form_for :picture, url: pictures_path do |f| %>
    <p>
      <%= f.label :Titulo %><br>
      <%= f.text_field :title %>
    </p>

    <p align="center">
      <%= f.file_field :avatar %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

TestApp/app/views/pictures/show.html.erb
<h1> Imagen: <%= @picture.title %></h1>
<%= image_tag @picture.avatar.url %>

TestApp/app/views/posts/index.html.erb
<h1>Todos los Posts</h1>

<%= link_to 'Nuevo Post', new_post_path %>
<div class = "posts">
  <div class="ingresar">
    <h3>Filtrar</h3>
    <p>Para filtrar por tags, ponga el tag que corresponde. Sino ponga todos</p>
    <p>
      Ingrese Filtro:
      <input type='text' class='textInput' value='todos' />
    </p>
  </div>
    <table class='table'>
      <tr>
        <th>Titulo</th>
        <th>Autor</th>
        <th>Elegir</th>
        <th>Opciones</th>
      </tr>

      <% @post.each do |post| %>
        <tr class="post todos <%= post.tag1 %> <%= post.tag2 %> <%= post.tag3 %> <%= post.tag4 %> <%= post.tag5 %>" data-image="<%=  post.avatar.url(:thumb) %>">
          <td><%= post.title %></td>
          <td><%= post.user %></td>
          <td><button class = "change"> Esta </button></td>
          <td><%= link_to 'Show', post_path(post) %></td>
        </tr>
      <% end %>


    </table>

  <select id="animation_box">
    <optgroup label="Attention Seekers">
      <option value="bounce">bounce</option>
      <option value="flash">flash</option>
      <option value="pulse">pulse</option>
      <option value="rubberBand">rubberBand</option>
      <option value="shake">shake</option>
      <option value="swing">swing</option>
      <option value="tada">tada</option>
      <option value="wobble">wobble</option>
    </optgroup>

    <optgroup label="Bouncing Entrances">
      <option value="bounceIn">bounceIn</option>
      <option value="bounceInDown">bounceInDown</option>
      <option value="bounceInLeft">bounceInLeft</option>
      <option value="bounceInRight">bounceInRight</option>
      <option value="bounceInUp">bounceInUp</option>
    </optgroup>

    <optgroup label="Bouncing Exits">
      <option value="bounceOut">bounceOut</option>
      <option value="bounceOutDown">bounceOutDown</option>
      <option value="bounceOutLeft">bounceOutLeft</option>
      <option value="bounceOutRight">bounceOutRight</option>
      <option value="bounceOutUp">bounceOutUp</option>
    </optgroup>

    <optgroup label="Fading Entrances">
      <option value="fadeIn">fadeIn</option>
      <option value="fadeInDown">fadeInDown</option>
      <option value="fadeInDownBig">fadeInDownBig</option>
      <option value="fadeInLeft">fadeInLeft</option>
      <option value="fadeInLeftBig">fadeInLeftBig</option>
      <option value="fadeInRight">fadeInRight</option>
      <option value="fadeInRightBig">fadeInRightBig</option>
      <option value="fadeInUp">fadeInUp</option>
      <option value="fadeInUpBig">fadeInUpBig</option>
    </optgroup>

    <optgroup label="Fading Exits">
      <option value="fadeOut">fadeOut</option>
      <option value="fadeOutDown">fadeOutDown</option>
      <option value="fadeOutDownBig">fadeOutDownBig</option>
      <option value="fadeOutLeft">fadeOutLeft</option>
      <option value="fadeOutLeftBig">fadeOutLeftBig</option>
      <option value="fadeOutRight">fadeOutRight</option>
      <option value="fadeOutRightBig">fadeOutRightBig</option>
      <option value="fadeOutUp">fadeOutUp</option>
      <option value="fadeOutUpBig">fadeOutUpBig</option>
    </optgroup>

    <optgroup label="Flippers">
      <option value="flip">flip</option>
      <option value="flipInX">flipInX</option>
      <option value="flipInY">flipInY</option>
      <option value="flipOutX">flipOutX</option>
      <option value="flipOutY">flipOutY</option>
    </optgroup>

    <optgroup label="Lightspeed">
      <option value="lightSpeedIn">lightSpeedIn</option>
      <option value="lightSpeedOut">lightSpeedOut</option>
    </optgroup>

    <optgroup label="Rotating Entrances">
      <option value="rotateIn">rotateIn</option>
      <option value="rotateInDownLeft">rotateInDownLeft</option>
      <option value="rotateInDownRight">rotateInDownRight</option>
      <option value="rotateInUpLeft">rotateInUpLeft</option>
      <option value="rotateInUpRight">rotateInUpRight</option>
    </optgroup>

    <optgroup label="Rotating Exits">
      <option value="rotateOut">rotateOut</option>
      <option value="rotateOutDownLeft">rotateOutDownLeft</option>
      <option value="rotateOutDownRight">rotateOutDownRight</option>
      <option value="rotateOutUpLeft">rotateOutUpLeft</option>
      <option value="rotateOutUpRight">rotateOutUpRight</option>
    </optgroup>

    <optgroup label="Specials">
      <option value="hinge">hinge</option>
      <option value="rollIn">rollIn</option>
      <option value="rollOut">rollOut</option>
    </optgroup>

    <optgroup label="Zoom Entrances">
      <option value="zoomIn">zoomIn</option>
      <option value="zoomInDown">zoomInDown</option>
      <option value="zoomInLeft">zoomInLeft</option>
      <option value="zoomInRight">zoomInRight</option>
      <option value="zoomInUp">zoomInUp</option>
    </optgroup>

    <optgroup label="Zoom Exits">
      <option value="zoomOut">zoomOut</option>
      <option value="zoomOutDown">zoomOutDown</option>
      <option value="zoomOutLeft">zoomOutLeft</option>
      <option value="zoomOutRight">zoomOutRight</option>
      <option value="zoomOutUp">zoomOutUp</option>
    </optgroup>
  </select>
  <button id = "animate"> Animar </button>
  <img id="image_box" class= "animate_box" src="3" alt="agregar imagen" style="width:720px;height:228px">

</div>

TestApp/app/views/posts/new.html.erb
<h1 align="center">Nuevo Post</h1>

<%= form_for :post, url: posts_path do |f| %>
    <p align="center">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p align="center">
      <%= f.label :user %><br>
      <%= f.text_field :user %>
    </p>

    <p align="center">
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p align="center">
      <%= f.label :tag1 %><br>
      <%= f.text_field :tag1 %>
    </p>

    <p align="center">
      <%= f.label :tag2 %><br>
      <%= f.text_field :tag2 %>
    </p>

    <p align="center">
      <%= f.label :tag3 %><br>
      <%= f.text_field :tag3 %>
    </p>

    <p align="center">
      <%= f.label :tag4 %><br>
      <%= f.text_field :tag4 %>
    </p>

    <p align="center">
      <%= f.label :tag5 %><br>
      <%= f.text_field :tag5 %>
    </p>

    <p align="center">
      <%= f.submit %>
    </p>

    <p align="center">
      <%= f.file_field :avatar %>
    </p>
<% end %>

<%= link_to 'Volver', posts_path %>

TestApp/app/views/posts/newFile.html.erb
<%= form_for(@invoice, :url=>invoices_path, :html => { :multipart => true,:id=>"fileupload"}) do |f| %>
    <legend>Create Invoice</legend>
    <%= invoice_form.label :invoice %>
    <p>Select or drap and drop files</p>
    <div id="browse_file">
      <%= f.file_field :invoice %>
    </div>
    <!-- The loading indicator is shown during image processing -->
    <div class="fileupload-loading"></div>
    <div id="uploaded">
      <table class="uploaded_files">

        <table>
    </div>
    <br>
    <!-- The table listing the files available for upload/download -->
    <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
    </table>
<%end%>
</div>

<%= f.submit "Invoice", :class=>"btn btn-success" %>
<%end%>

</div>
</div>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  <tr class="template-upload fade">
    <td class="name"><span>{%=file.name%}</span></td>
    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
    {% if (file.error) { %}
    <td class="error"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
    {% } else if (o.files.valid && !i) { %}
    {% } else { %}
    {% } %}
    <td>
      <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
    </td>
  </tr>
  {% } %}

</script>

<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
      {% if (file.error) { %}
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
        <td class="name">
          <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}" class='downloadable'>{%=file.name%}</a>
        </td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        {% } %}
      <td></td>
      <td class="delete">
        <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
          <i class="icon-trash icon-white"></i>
          <span>{%=locale.fileupload.destroy%}</span>
        </button>
      </td>
    </tr>
    {% } %}
</script>

<script type="text/javascript" charset="utf-8">

    $(function() {
        $("#fileupload").fileupload({
            autoUpload: true,
            acceptFileTypes: /(\.|\/)(docx?|pdf)$/i,
            url: '/invoices/upload_file'
        });
        return $.getJSON($("#fileupload").prop("action"), function(files) {
            var fu, template;
            fu = $("#fileupload").data("blueimpFileupload");
            template = void 0;
            fu._adjustMaxNumberOfFiles(-files.length);
            template = fu._renderDownload(files).appendTo($("#fileupload .files"));
            fu._reflow = fu._transition && template.length && template[0].offsetWidth;
            template.addClass("in");
            return $("#loading").remove();
        });
    });


</script>

TestApp/app/views/posts/show.html.erb
<% if @post.errors.any?  %>
  <% @post.errors.each do |error| %>
    <p>Hubo un error  <%= error.message %> </p>
  <% end %>
<% end %>

<p>
  <strong>Titulo:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @post.user %>
</p>

<p>
  <strong>Post:</strong>
  <%= @post.text %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @post.tag1 %> , <%= @post.tag2 %> , <%= @post.tag3 %> , <%= @post.tag4 %> , <%= @post.tag5 %>
</p>
<p>
  <strong>Imagen:</strong>
  <%= image_tag @post.avatar.url(:thumb) %>
</p>

<h2>Comentarios</h2>
<% @post.comments.each do |comment| %>
    <% if comment.errors.any?  %>
      <ul>
        <% comment.errors.full_messages do |msg| %>
          <li>Hubo un error:  <%= msg %> </li>
        <% end %>
      </ul>
    <% end %>

    <p>
      <strong>Usuario:</strong>
      <%= comment.user %>
    </p>

    <p>
      <strong>Comentario:</strong>
      <%= comment.body %>
    </p>


    <%= button_to post_comment_path(post_id: @post.id, id: comment.id), method: :delete, class: "btn btn-danger" do%>
      <i class='fa fa-trash'></i>
    <% end %>

<% end %>

<h2>Agrega un Comentario:</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
      <%= f.label :user %><br>
      <%= f.text_field :user %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

<%= link_to 'Volver', posts_path %>

TestApp/app/views/welcome/index.html.erb
<h1>Hola, bienvenidos!</h1>
Bienvenidos al blog de testeo.
<%= link_to 'El Blog', controller: 'posts' %>